/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    EpSetting: typeof import('~icons/ep/setting')['default']
    EpSunny: typeof import('~icons/ep/sunny')['default']
    HeaderPage: typeof import('./src/components/HeaderPage.vue')['default']
    IconData: typeof import('./src/components/icons/IconData.vue')['default']
    IconManagement: typeof import('./src/components/icons/IconManagement.vue')['default']
    IconMessages: typeof import('./src/components/icons/IconMessages.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    LoadingComponent: typeof import('./src/components/LoadingComponent.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NotificationBar: typeof import('./src/components/NotificationBar.vue')['default']
    NotLogIn: typeof import('./src/components/NotLogIn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TabBarItem: typeof import('./src/components/TabBarItem.vue')['default']
  }
}
