/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppView: typeof import('./src/components/AppView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconData: typeof import('./src/components/icons/IconData.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconManagement: typeof import('./src/components/icons/IconManagement.vue')['default']
    IconMessages: typeof import('./src/components/icons/IconMessages.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NavigatorBar: typeof import('./src/components/NavigatorBar.vue')['default']
    NotificationBar: typeof import('./src/components/NotificationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TabBarItem: typeof import('./src/components/TabBarItem.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
